### ISSUE TITLE
Wrong token probabilities calculation?

### ISSUE THREAD

**Issue by Shaier** [swj0419/detect-pretrain-code#5]
Hi,
I think you are calculating the token probabilities incorrectly. But please correct me if I'm wrong.
This is how you calculate the probabilities as far as I know:
```
def calculatePerplexity(sentence, model, tokenizer, gpu):
    """
    exp(loss)
    """
    input_ids = torch.tensor(tokenizer.encode(sentence)).unsqueeze(0)
    input_ids = input_ids.to(gpu)
    with torch.no_grad():
        outputs = model(input_ids, labels=input_ids)
    loss, logits = outputs[:2]
    
    '''
    extract logits:
    '''
    # Apply softmax to the logits to get probabilities
    probabilities = torch.nn.functional.log_softmax(logits, dim=-1)
    # probabilities = torch.nn.functional.softmax(logits, dim=-1)
    all_prob = []
    input_ids_processed = input_ids[0][1:]
    for i, token_id in enumerate(input_ids_processed):
        probability = probabilities[0, i, token_id].item()
        all_prob.append(probability)
    return torch.exp(loss).item(), all_prob, loss.item()

```
You only calculate the token probabilities starting from the first token:
`input_ids_processed = input_ids[0][1:]`
But then to get the probabilities you iterate through the "probabilities" variable starting at index 0 and not 1:
  ```
  for i, token_id in enumerate(input_ids_processed):
        probability = probabilities[0, i, token_id].item() # I think that "i" should start at 1 here
```
This means that you are getting the probabilities of wrong tokens. You can see it by simply adding +1 to the index and see that it doesn't causes an error (if you were calculating it correctly this should result in "IndexError"

` for i, token_id in enumerate(input_ids_processed):
        probability = probabilities[0, i+1, token_id].item()`

If this is the case your entire premise that the MIN-K% is outperforming existing methods might be wrong or off... 
Again, I might be wrong so please correct me if I'm misunderstanding something

**Comment by swj0419** [comment]
**We compute the token probabilities in the right way**
Considering tokenizers such as the LLaMA tokenizer, which would add a special start of sentence token, it's important to note that a language model's output probabilities represent the likelihood of each subsequent token given the previous tokens in a sequence. This means that for the first token in a sentence, the model calculates its probability based on the start of sentence token alone. For each following token, the probability is conditioned on the full context of all preceding tokens, up to a certain context window limit imposed by the model's design

**Comment by Shaier** [comment]
Can you clarify what you mean by "subsequent"? If we have a sequence of 4 tokens (e.g., [0, 78,42,23]) where the first one (e.g., 0) is the start token, your "probabilities" tensor will be of size (1,4,vocab_size). Are you saying that the first index of the "probabilities" tensor -- probabilities[0, 0, 78] -- is the probability of the token 78 conditioned on the start token? And the second index -- probabilities[0, 1, 42] -- is the probability of the token 42 conditioned on the start token and token 78?

**Comment by swj0419** [comment]
Yes, that is right. And the last token probability is used to predict the next token given the sequence

**Comment by Shaier** [comment]
Got it! Thanks a lot for the great work and explanation!
